name: Release

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macOS-latest
            target: x86_64-apple-darwin
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Set the version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      shell: bash

    - name: Build
      run: cargo build --release --locked

    - name: Strip binary
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: strip target/release/qurl

    - name: Package
      shell: bash
      run: |
        # package
        EXE_suffix="" ; case ${{ matrix.target }} in *-pc-windows-*) EXE_suffix=".exe" ;; esac;
        cp target/release/qurl${{ EXE_suffix }} ./qurl${{ EXE_suffix }}
        case ${{ matrix.target }} in
          *-windows-*) 7z -y a 'qurl-${{ steps.version.outputs.VERSION }}-${{ matrix.target }}.zip' 'qurl.exe' 'README.md' 'LICENSE' | tail -2 ;;
          *) zip 'qurl-${{ steps.version.outputs.VERSION }}-${{ matrix.target }}.zip' 'qurl' 'README.md' 'LICENSE' ;;
        esac;

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: qurl-${{ steps.version.outputs.VERSION }}-${{ matrix.target }}.zip
        asset_name: qurl-${{ steps.version.outputs.VERSION }}-${{ matrix.target }}.zip
        tag: ${{ github.ref }}
